---
framework: jasmine
parallelism: 3
blocklist:
 - "spec/JUnitXmlReporterSpec.js"
postMerge:
  pattern:
    - "./spec/**/*Spec.js"
preMerge:
  pattern:
    - "./spec/**/*Spec.js"
preRun:
 command:
  - npm i
postRun:
 command:
  - node --version
version: 1.5
  
